import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-expect-error this is a CSS module
import "./globals.css";
import Header from "@/components/Header";
import Navigation from "@/components/Navigation";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster position="top-center" />
        <div className="flex h-screen bg-white text-gray-800">
          {/* Navigation */}
          <Navigation />

          {/* Main Content */}
          <main className="flex-1 flex flex-col h-svh overflow-hidden">
            {/* Header */}
            <Header />

            {/* Empty Content Area */}
            <div className="flex-1 flex">
              {children}
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
